// EHVM Deal Desk — SAMPLE seed data (clearly labeled). Working-concept figures only.

export type Stage =
  | "Sourced"
  | "Listed"
  | "Buyer Matching"
  | "LOI / Due Diligence"
  | "Closed";

export const STAGES: Stage[] = [
  "Sourced",
  "Listed",
  "Buyer Matching",
  "LOI / Due Diligence",
  "Closed",
];

export type Category =
  | "AI"
  | "Game"
  | "Productivity"
  | "Health"
  | "Education"
  | "Finance";

export const CATEGORY_COLOR: Record<
  Category,
  { fg: string; bg: string }
> = {
  AI: { fg: "var(--color-purple)", bg: "var(--color-purple-soft)" },
  Game: { fg: "var(--color-pink)", bg: "var(--color-pink-soft)" },
  Productivity: { fg: "var(--color-blue)", bg: "var(--color-blue-soft)" },
  Health: { fg: "var(--color-green)", bg: "var(--color-green-soft)" },
  Education: { fg: "var(--color-orange)", bg: "var(--color-orange-soft)" },
  Finance: { fg: "var(--color-ink-soft)", bg: "var(--color-line)" },
};

export const STAGE_COLOR: Record<Stage, { fg: string; bg: string }> = {
  Sourced: { fg: "var(--color-ink-soft)", bg: "var(--color-line)" },
  Listed: { fg: "var(--color-blue)", bg: "var(--color-blue-soft)" },
  "Buyer Matching": { fg: "var(--color-orange)", bg: "var(--color-orange-soft)" },
  "LOI / Due Diligence": { fg: "var(--color-purple)", bg: "var(--color-purple-soft)" },
  Closed: { fg: "var(--color-green)", bg: "var(--color-green-soft)" },
};

export type DiligenceItem = {
  label: string;
  ready: boolean;
};

export type Deal = {
  id: string;
  name: string;
  blurb: string;
  category: Category;
  platform: "iOS" | "Android" | "Cross-platform";
  stage: Stage;
  arr: number; // annual recurring revenue, USD
  mrr: number; // monthly recurring revenue, USD
  mrrMultiple: number; // asking / (mrr*12) expressed as MRR multiple
  ebitdaMultiple: number;
  d30: number; // % retention
  d90: number; // % retention
  churn: number; // monthly %, total
  involuntaryChurnShare: number; // share of churn that is involuntary, %
  mau: number;
  dau: number;
  ltv: number;
  cac: number;
  paybackMonths: number;
  organicShare: number; // % of installs that are organic
  asking: number; // USD
  // 6-month retention cohort curve (D0..D180), % of cohort still active
  cohort: number[];
  diligence: DiligenceItem[];
};

// asking prices roughly sum to $438M+ to mirror her portfolio figure.
export const DEALS: Deal[] = [
  {
    id: "lumina",
    name: "Lumina",
    blurb: "AI photo editor with on-device relighting & generative cleanup.",
    category: "AI",
    platform: "iOS",
    stage: "Buyer Matching",
    arr: 2_400_000,
    mrr: 200_000,
    mrrMultiple: 4.6,
    ebitdaMultiple: 6.1,
    d30: 38,
    d90: 19,
    churn: 7.4,
    involuntaryChurnShare: 31,
    mau: 1_280_000,
    dau: 214_000,
    ltv: 41,
    cac: 12,
    paybackMonths: 2.6,
    organicShare: 64,
    asking: 9_800_000,
    cohort: [100, 61, 47, 38, 31, 24, 19],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: true },
      { label: "Experiment log", ready: false },
      { label: "App Store transfer ready", ready: true },
      { label: "Subscription cohort export", ready: false },
    ],
  },
  {
    id: "mergekingdom",
    name: "MergeKingdom",
    blurb: "Merge-2 casual game; live-ops events & battle-pass economy.",
    category: "Game",
    platform: "Cross-platform",
    stage: "LOI / Due Diligence",
    arr: 11_000_000,
    mrr: 916_000,
    mrrMultiple: 3.8,
    ebitdaMultiple: 5.4,
    d30: 29,
    d90: 21,
    churn: 9.1,
    involuntaryChurnShare: 18,
    mau: 3_900_000,
    dau: 720_000,
    ltv: 28,
    cac: 9,
    paybackMonths: 3.1,
    organicShare: 41,
    asking: 20_000_000,
    cohort: [100, 52, 38, 29, 25, 22, 21],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: true },
      { label: "Experiment log", ready: true },
      { label: "Ad-network revenue proof", ready: true },
      { label: "Source & art assets escrow", ready: false },
    ],
  },
  {
    id: "focusflow",
    name: "FocusFlow",
    blurb: "Pomodoro + focus-sounds productivity app, small but profitable.",
    category: "Productivity",
    platform: "iOS",
    stage: "Listed",
    arr: 180_000,
    mrr: 15_000,
    mrrMultiple: 3.2,
    ebitdaMultiple: 3.9,
    d30: 34,
    d90: 17,
    churn: 6.2,
    involuntaryChurnShare: 27,
    mau: 96_000,
    dau: 18_500,
    ltv: 33,
    cac: 8,
    paybackMonths: 2.2,
    organicShare: 78,
    asking: 150_000,
    cohort: [100, 58, 43, 34, 26, 21, 17],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: false },
      { label: "Experiment log", ready: false },
      { label: "App Store transfer ready", ready: true },
    ],
  },
  {
    id: "vitalsleep",
    name: "VitalSleep",
    blurb: "Sleep-tracking & soundscape app with HealthKit integration.",
    category: "Health",
    platform: "Cross-platform",
    stage: "Sourced",
    arr: 3_600_000,
    mrr: 300_000,
    mrrMultiple: 4.1,
    ebitdaMultiple: 5.8,
    d30: 41,
    d90: 24,
    churn: 5.4,
    involuntaryChurnShare: 34,
    mau: 870_000,
    dau: 198_000,
    ltv: 54,
    cac: 16,
    paybackMonths: 3.4,
    organicShare: 57,
    asking: 14_700_000,
    cohort: [100, 64, 51, 41, 33, 28, 24],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: false },
      { label: "Handover docs", ready: false },
      { label: "Experiment log", ready: false },
      { label: "HIPAA / data-handling review", ready: false },
    ],
  },
  {
    id: "wordrush",
    name: "WordRush",
    blurb: "Daily word-puzzle game with social leagues & streaks.",
    category: "Game",
    platform: "Android",
    stage: "Buyer Matching",
    arr: 5_200_000,
    mrr: 433_000,
    mrrMultiple: 3.5,
    ebitdaMultiple: 4.7,
    d30: 33,
    d90: 22,
    churn: 8.0,
    involuntaryChurnShare: 22,
    mau: 2_100_000,
    dau: 460_000,
    ltv: 24,
    cac: 7,
    paybackMonths: 2.4,
    organicShare: 49,
    asking: 8_900_000,
    cohort: [100, 56, 42, 33, 28, 24, 22],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: true },
      { label: "Experiment log", ready: false },
      { label: "Play Console transfer ready", ready: true },
    ],
  },
  {
    id: "tutorpod",
    name: "TutorPod",
    blurb: "Adaptive K-12 math tutoring app; B2C subs + school licenses.",
    category: "Education",
    platform: "iOS",
    stage: "LOI / Due Diligence",
    arr: 6_800_000,
    mrr: 566_000,
    mrrMultiple: 4.3,
    ebitdaMultiple: 6.0,
    d30: 44,
    d90: 28,
    churn: 4.9,
    involuntaryChurnShare: 41,
    mau: 540_000,
    dau: 132_000,
    ltv: 68,
    cac: 21,
    paybackMonths: 3.6,
    organicShare: 52,
    asking: 21_500_000,
    cohort: [100, 67, 55, 44, 36, 31, 28],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: true },
      { label: "Experiment log", ready: true },
      { label: "School-contract assignability", ready: false },
    ],
  },
  {
    id: "coinkeeper",
    name: "CoinKeeper",
    blurb: "Personal-budgeting app, open-banking aggregation, EU + US.",
    category: "Finance",
    platform: "Cross-platform",
    stage: "Closed",
    arr: 4_100_000,
    mrr: 341_000,
    mrrMultiple: 4.0,
    ebitdaMultiple: 5.5,
    d30: 47,
    d90: 31,
    churn: 4.2,
    involuntaryChurnShare: 29,
    mau: 610_000,
    dau: 162_000,
    ltv: 72,
    cac: 19,
    paybackMonths: 3.2,
    organicShare: 60,
    asking: 16_400_000,
    cohort: [100, 70, 58, 47, 39, 34, 31],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: true },
      { label: "Experiment log", ready: true },
      { label: "PSD2 / open-banking licenses", ready: true },
    ],
  },
  {
    id: "pixelfarm",
    name: "PixelFarm",
    blurb: "Cozy farming sim; strong organic TikTok-driven installs.",
    category: "Game",
    platform: "Cross-platform",
    stage: "Listed",
    arr: 7_900_000,
    mrr: 658_000,
    mrrMultiple: 3.6,
    ebitdaMultiple: 4.9,
    d30: 36,
    d90: 23,
    churn: 7.8,
    involuntaryChurnShare: 20,
    mau: 2_650_000,
    dau: 590_000,
    ltv: 26,
    cac: 6,
    paybackMonths: 1.9,
    organicShare: 71,
    asking: 13_900_000,
    cohort: [100, 59, 44, 36, 30, 26, 23],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: false },
      { label: "Experiment log", ready: true },
      { label: "Source & art assets escrow", ready: false },
    ],
  },
  {
    id: "speakeasy",
    name: "SpeakEasy",
    blurb: "AI language-tutor with voice; conversation-practice subs.",
    category: "AI",
    platform: "Cross-platform",
    stage: "Sourced",
    arr: 9_300_000,
    mrr: 775_000,
    mrrMultiple: 4.8,
    ebitdaMultiple: 6.4,
    d30: 40,
    d90: 26,
    churn: 5.7,
    involuntaryChurnShare: 33,
    mau: 1_540_000,
    dau: 340_000,
    ltv: 58,
    cac: 17,
    paybackMonths: 3.0,
    organicShare: 45,
    asking: 31_200_000,
    cohort: [100, 63, 50, 40, 33, 29, 26],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: false },
      { label: "Handover docs", ready: false },
      { label: "Experiment log", ready: true },
      { label: "Model / inference cost breakdown", ready: false },
    ],
  },
  {
    id: "zenscape",
    name: "Zenscape",
    blurb: "Meditation & breathwork app, premium content library.",
    category: "Health",
    platform: "iOS",
    stage: "Buyer Matching",
    arr: 12_600_000,
    mrr: 1_050_000,
    mrrMultiple: 4.4,
    ebitdaMultiple: 6.2,
    d30: 43,
    d90: 27,
    churn: 4.6,
    involuntaryChurnShare: 36,
    mau: 1_960_000,
    dau: 470_000,
    ltv: 64,
    cac: 18,
    paybackMonths: 3.3,
    organicShare: 55,
    asking: 58_900_000,
    cohort: [100, 66, 53, 43, 35, 30, 27],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: true },
      { label: "Experiment log", ready: false },
      { label: "Content licensing chain", ready: true },
    ],
  },
  {
    id: "rallyracer",
    name: "RallyRacer",
    blurb: "Arcade racing game; IAP + rewarded-ads hybrid monetization.",
    category: "Game",
    platform: "Cross-platform",
    stage: "LOI / Due Diligence",
    arr: 18_400_000,
    mrr: 1_533_000,
    mrrMultiple: 3.7,
    ebitdaMultiple: 5.0,
    d30: 31,
    d90: 20,
    churn: 8.6,
    involuntaryChurnShare: 19,
    mau: 5_200_000,
    dau: 1_010_000,
    ltv: 22,
    cac: 6,
    paybackMonths: 2.1,
    organicShare: 38,
    asking: 41_600_000,
    cohort: [100, 53, 40, 31, 26, 23, 20],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: true },
      { label: "Experiment log", ready: true },
      { label: "Source & art assets escrow", ready: true },
      { label: "Ad-network revenue proof", ready: true },
    ],
  },
  {
    id: "scanflow",
    name: "ScanFlow",
    blurb: "AI document-scanner & OCR; prosumer + small-business subs.",
    category: "AI",
    platform: "iOS",
    stage: "Sourced",
    arr: 14_200_000,
    mrr: 1_183_000,
    mrrMultiple: 4.5,
    ebitdaMultiple: 6.3,
    d30: 39,
    d90: 25,
    churn: 5.1,
    involuntaryChurnShare: 35,
    mau: 2_240_000,
    dau: 410_000,
    ltv: 51,
    cac: 15,
    paybackMonths: 2.9,
    organicShare: 62,
    asking: 66_700_000,
    cohort: [100, 62, 49, 39, 32, 28, 25],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: false },
      { label: "Handover docs", ready: true },
      { label: "Experiment log", ready: false },
      { label: "Model / inference cost breakdown", ready: true },
    ],
  },
  {
    id: "habitloop",
    name: "HabitLoop",
    blurb: "Habit-tracker with streak insurance & social accountability.",
    category: "Productivity",
    platform: "Cross-platform",
    stage: "Listed",
    arr: 2_900_000,
    mrr: 241_000,
    mrrMultiple: 3.9,
    ebitdaMultiple: 4.6,
    d30: 37,
    d90: 21,
    churn: 6.0,
    involuntaryChurnShare: 28,
    mau: 720_000,
    dau: 158_000,
    ltv: 38,
    cac: 11,
    paybackMonths: 2.5,
    organicShare: 69,
    asking: 11_300_000,
    cohort: [100, 60, 45, 37, 29, 24, 21],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: true },
      { label: "Experiment log", ready: false },
      { label: "App Store transfer ready", ready: true },
    ],
  },
  {
    id: "mathmonsters",
    name: "MathMonsters",
    blurb: "Gamified early-math learning for ages 5-9; parent + kid modes.",
    category: "Education",
    platform: "iOS",
    stage: "Closed",
    arr: 4_700_000,
    mrr: 391_000,
    mrrMultiple: 4.2,
    ebitdaMultiple: 5.6,
    d30: 42,
    d90: 26,
    churn: 5.0,
    involuntaryChurnShare: 38,
    mau: 480_000,
    dau: 121_000,
    ltv: 61,
    cac: 20,
    paybackMonths: 3.5,
    organicShare: 50,
    asking: 18_600_000,
    cohort: [100, 65, 52, 42, 34, 30, 26],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: true },
      { label: "Experiment log", ready: true },
      { label: "COPPA / kids-privacy review", ready: true },
    ],
  },
  {
    id: "trailmate",
    name: "TrailMate",
    blurb: "Hiking & trail-tracking app with offline maps; outdoor niche.",
    category: "Health",
    platform: "Cross-platform",
    stage: "Buyer Matching",
    arr: 8_100_000,
    mrr: 675_000,
    mrrMultiple: 4.0,
    ebitdaMultiple: 5.3,
    d30: 35,
    d90: 22,
    churn: 6.4,
    involuntaryChurnShare: 30,
    mau: 1_120_000,
    dau: 214_000,
    ltv: 47,
    cac: 14,
    paybackMonths: 2.8,
    organicShare: 58,
    asking: 32_100_000,
    cohort: [100, 58, 45, 35, 29, 25, 22],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: true },
      { label: "Handover docs", ready: false },
      { label: "Experiment log", ready: true },
      { label: "Map-data licensing chain", ready: false },
    ],
  },
  {
    id: "investly",
    name: "Investly",
    blurb: "Micro-investing & round-ups app; brokerage partner integration.",
    category: "Finance",
    platform: "Cross-platform",
    stage: "Sourced",
    arr: 10_500_000,
    mrr: 875_000,
    mrrMultiple: 4.1,
    ebitdaMultiple: 5.7,
    d30: 45,
    d90: 29,
    churn: 4.4,
    involuntaryChurnShare: 32,
    mau: 980_000,
    dau: 240_000,
    ltv: 79,
    cac: 23,
    paybackMonths: 3.7,
    organicShare: 47,
    asking: 73_500_000,
    cohort: [100, 68, 56, 45, 37, 33, 29],
    diligence: [
      { label: "Clean P&L (24 mo)", ready: false },
      { label: "Handover docs", ready: false },
      { label: "Experiment log", ready: false },
      { label: "Broker-dealer agreement assignability", ready: false },
    ],
  },
];

export type Buyer = {
  id: string;
  name: string;
  type: "PE firm" | "App roll-up" | "Public co" | "Strategic";
  mandate: Category[];
  checkLow: number;
  checkHigh: number;
  note: string;
};

export const BUYERS: Buyer[] = [
  {
    id: "northpeak",
    name: "Northpeak Capital",
    type: "PE firm",
    mandate: ["AI", "Productivity", "Finance"],
    checkLow: 10_000_000,
    checkHigh: 75_000_000,
    note: "Buy-and-hold SaaS thesis; wants D30 > 35% and clean P&L.",
  },
  {
    id: "applevate",
    name: "Applevate Roll-up",
    type: "App roll-up",
    mandate: ["Productivity", "Health", "AI"],
    checkLow: 2_000_000,
    checkHigh: 25_000_000,
    note: "Aggregates prosumer subscription apps; fast close, asset deals.",
  },
  {
    id: "vertex",
    name: "Vertex Games Group",
    type: "Strategic",
    mandate: ["Game"],
    checkLow: 8_000_000,
    checkHigh: 60_000_000,
    note: "Live-ops studio; values proven ad + IAP hybrid economies.",
  },
  {
    id: "lumenpe",
    name: "Lumen Growth Partners",
    type: "PE firm",
    mandate: ["Health", "Education", "Finance"],
    checkLow: 15_000_000,
    checkHigh: 90_000_000,
    note: "Recurring-revenue focus; HealthKit/edu compliance comfortable.",
  },
  {
    id: "axiom",
    name: "Axiom Health (Public)",
    type: "Public co",
    mandate: ["Health"],
    checkLow: 20_000_000,
    checkHigh: 120_000_000,
    note: "Strategic; wants HealthKit data moat and clinical defensibility.",
  },
  {
    id: "scholar",
    name: "Scholar Learning Co.",
    type: "Public co",
    mandate: ["Education"],
    checkLow: 12_000_000,
    checkHigh: 70_000_000,
    note: "Edu strategic; needs COPPA-clean and school-contract assignability.",
  },
  {
    id: "ledger",
    name: "Ledger Fintech Partners",
    type: "PE firm",
    mandate: ["Finance", "AI"],
    checkLow: 18_000_000,
    checkHigh: 85_000_000,
    note: "Open-banking thesis; cares about license assignability + churn.",
  },
  {
    id: "pixelbridge",
    name: "PixelBridge Roll-up",
    type: "App roll-up",
    mandate: ["Game"],
    checkLow: 3_000_000,
    checkHigh: 22_000_000,
    note: "Casual-game aggregator; wants source + art escrow at close.",
  },
];
